from .triplet_margin import TripletLoss
from .dualcontrastive_CE import DualContrastiveLoss_CE
from .dualcontrastive_margin import DualContrastiveLoss
from .multicontrastive import MultiContrastiveLoss
from .contrastive_CE import ContrastiveLoss
from .contrastive_margin import ContrastiveLossMargin